### ISSUE TITLE
Add README.md, LICENSE, ASCNavigationBar.podspec and maybe .travis.yml

### ISSUE THREAD

**Issue by alexruperez** [acsanchezcu/ASCNavigationBar#1]
Hola Eibol!

Yo le metería estos archivos, creo que te serán útiles y le darán mas visibilidad al repo.

Te pongo ejemplos de un repo mío por si quieres basarte en ellos:
[README.md](https://github.com/alexruperez/UIUserNotificationSettings-Extension/blob/master/README.md) para presentar tu proyecto.
[LICENSE](https://github.com/alexruperez/UIUserNotificationSettings-Extension/blob/master/LICENSE) para indicar el tipo de licencia [Open Source](http://opensource.org/licenses/MIT).
[podspec](https://github.com/alexruperez/UIUserNotificationSettings-Extension/blob/master/UIUserNotificationSettings-Extension.podspec) para que se pueda instalar con [CocoaPods](https://guides.cocoapods.org/making/specs-and-specs-repo.html).
[.travis.yml](https://github.com/alexruperez/UIUserNotificationSettings-Extension/blob/master/.travis.yml) para hacer integración continua gratis con [Travis CI](http://docs.travis-ci.com/user/languages/objective-c/).

Un abrazo amigo!

**Comment by acsanchezcu** [comment]
@alexruperez Cooool, me lo apunto tio, muchas gracias :D
